# Generated by Django 4.2.1 on 2023-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
